---
#global settings
my_server_id: 100
replica_batch_size: 1000
copy_max_memory: 300M
my_database:  db_replica
pg_database: db_replication
copy_mode: 'file' 
#copy_mode: 'direct'

hexify: 
    - 'blob'
    - 'tinyblob'
    - 'longblob'
    - 'binary'

log_dir: 'logs/'
log_level: 'debug'
log_dest: 'stdout'
#log_dest: 'file'
#log_level: 'info'
#log_level: 'debug'


#mysql connection's charset. 
my_charset: 'utf8'
#postgresql connection's charset. 
pg_charset: 'utf8'
#include tables only
tables_limit:
    

#mysql slave setup
mysql_conn:
    host: localhost
    port: 3306
    user: replication_username
    passwd: never_commit_passwords

#postgres connection
pg_conn:
    host: localhost
    port: 5432
    user: replication_username
    password: never_commit_passwords
 
